### ISSUE TITLE
We dont know how to use this.

### ISSUE THREAD

**Issue by Thehelper104** [MaximumADHD/Roblox-API-Dump-Tool#1]
How?

**Comment by MaximumADHD** [comment]
Hmm, yeah I do need to write a README section for this. I'll take care of it in a bit.

You can download the program from the Releases page:
https://github.com/CloneTrooper1019/Roblox-API-Dump-Tool/releases

The purpose of this program is to view a listing of Roblox's Lua API. 
It also provides the option to compare API Dumps so you can see upcoming changes to Roblox's Lua API.

**Comment by Thehelper104** [comment]
oh yeah and also.. gametest 5, 4, 3, 2, and 1 cant be accessed using your mod manager! youll need to release them.

**Comment by MaximumADHD** [comment]
Finally got around to adding the readme file.
